version: '3.8'

services:
  php_eduall:
    build:
      context: ./eduall
      dockerfile: Dockerfile
    container_name: php_eduall
    networks:
      - app-network
    ports:
      - "9001:9000"
    expose:
      - "8181"

  php_junior:
    build:
      context: ./junior
      dockerfile: Dockerfile
    container_name: php_junior
    networks:
      - app-network
    ports:
      - "9002:9000"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - php_eduall
      - php_junior

networks:
  app-network:
    driver: bridge