version: '3.8'

services:
  php_eduall:
    build:
      context: ./eduall
      dockerfile: Dockerfile
    container_name: php_eduall
    networks:
      - app-network
    ports:
      - "9001:9000"

  php_junior:
    build:
      context: ./junior
      dockerfile: Dockerfile
    container_name: php_junior
    networks:
      - app-network
    ports:
      - "9002:9000"

  php_timesheet:
    build:
      context: ./timesheet
      dockerfile: Dockerfile
    container_name: php_timesheet
    networks:
      - app-network
    ports:
      - "9003:9000"

  php_assessment:
    build:
      context: ./assessment
      dockerfile: Dockerfile
    container_name: php_assessment
    networks:
      - app-network
    ports:
      - "9004:9000"
  
  php_editing:
    build:
      context: ./editing
      dockerfile: Dockerfile
    container_name: php_editing
    networks:
      - app-network
    ports:
      - "9005:9000"

  php_crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: php_crm
    networks:
      - app-network
    ports:
      - "9006:9000"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/all-inedu.com/fullchain.pem:/etc/letsencrypt/live/all-inedu.com/fullchain.pem
      - /etc/letsencrypt/live/all-inedu.com/privkey.pem:/etc/letsencrypt/live/all-inedu.com/privkey.pem
      - ./eduall/src:/eduall
      - ./registration/src:/registration
      - ./junior/src:/junior
      - ./timesheet/src:/timesheet
      - ./assessment/src:/assessment
      - ./editing/src:/editing
      - ./crm/src:/crm
    networks:
      - app-network
    depends_on:
      - php_eduall
      - php_junior
      - php_timesheet
      - php_assessment
      - php_editing
      - php_crm

networks:
  app-network:
    driver: bridge