version: '3.8'

services:
  php_eduall:
    build:
      context: ./eduall
      dockerfile: Dockerfile
    container_name: php_eduall
    volumes:
      - ./eduall/src:/eduall
      - ./eduall/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9001:9000"

  php_junior:
    build:
      context: ./junior
      dockerfile: Dockerfile
    container_name: php_junior
    volumes:
      - ./junior/src:/junior
      - ./junior/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9002:9000"

  php_timesheet:
    build:
      context: ./timesheet
      dockerfile: Dockerfile
    container_name: php_timesheet
    volumes:
      - ./timesheet/src:/timesheet
      - ./timesheet/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9003:9000"

  php_assessment:
    build:
      context: ./assessment
      dockerfile: Dockerfile
    container_name: php_assessment
    volumes:
      - ./assessment/src:/assessment
      - ./assessment/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9004:9000"
  
  php_editing:
    build:
      context: ./editing
      dockerfile: Dockerfile
    container_name: php_editing
    volumes:
      - ./editing/src:/editing
      - ./editing/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9005:9000"

  php_crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: php_crm
    volumes:
      - ./crm/src:/crm
      - ./crm/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9006:9000"

  staging_php_crm:
    build:
      context: ./staging-crm
      dockerfile: Dockerfile
    container_name: staging_php_crm
    volumes:
      - ./staging-crm/src:/staging-crm
      - ./staging-crm/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9007:9000"

  php_editing_v2:
    build:
      context: ./editing_v2/back-end
      dockerfile: Dockerfile
    container_name: php_editing_v2
    volumes:
      - ./editing_v2/back-end/src:/editing_v2/back-end
      - ./editing_v2/back-end/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9008:9000"

  php_mentoring:
    build:
      context: ./mentoring/back-end
      dockerfile: Dockerfile
    container_name: php_mentoring
    volumes:
      - ./mentoring/back-end/src:/mentoring/back-end
      - ./mentoring/back-end/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9009:9000"

  php_authorization:
    build:
      context: ./authorization
      dockerfile: Dockerfile
    container_name: php_authorization
    volumes:
      - ./authorization/src:/authorization
      - ./authorization/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    networks:
      - app-network
    ports:
      - "9010:9000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    networks:
      - app-network
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - app-network
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    ports:
      - "5601:5601"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/queue.sh:/queue.sh
      - ./nginx/cron/cronfile:/etc/cron.d/cronfile
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/security.conf:/etc/nginx/security.conf
      - ./nginx/general.conf:/etc/nginx/general.conf
      - /etc/letsencrypt/archive/edu-all.com/fullchain1.pem:/etc/letsencrypt/live/edu-all.com/fullchain1.pem
      - /etc/letsencrypt/archive/edu-all.com/privkey1.pem:/etc/letsencrypt/live/edu-all.com/privkey1.pem
      - ./eduall/src:/eduall
      - ./registration/src:/registration
      - ./junior/src:/junior
      - ./timesheet/src:/timesheet
      - ./assessment/src:/assessment
      - ./editing/src:/editing
      - ./crm/src:/crm
      - ./staging-crm/src:/staging-crm
      - ./mentoring/front-end/src:/mentoring/front-end
      - ./mentoring/back-end/src:/mentoring/back-end
      - ./editing_v2/back-end/src:/editing_v2/back-end
      - ./editing_v2/front-end/src:/editing_v2/front-end
      - ./authorization/src:/authorization
    networks:
      - app-network
    depends_on:
      - php_eduall
      - php_junior
      - php_timesheet
      - php_assessment
      - php_editing
      - php_crm
      - staging_php_crm
      - php_editing_v2
      - php_mentoring
      - php_authorization
      - kibana

networks:
  app-network:
    driver: bridge