version: '3.8'

services:
  php_eduall:
    build:
      context: ./eduall
      dockerfile: Dockerfile
    container_name: php_eduall
    networks:
      - app-network
    ports:
      - "9001:9000"
    expose:
      - "8181"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/all-inedu.com/fullchain.pem:/etc/letsencrypt/live/all-inedu.com/fullchain.pem
      - /etc/letsencrypt/live/all-inedu.com/privkey.pem:/etc/letsencrypt/live/all-inedu.com/privkey.pem
      - ./eduall/src:/eduall
      - ./registration/src:/registration
    networks:
      - app-network
    depends_on:
      - php_eduall

networks:
  app-network:
    driver: bridge