server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1024000
    batchwait: 1s

scrape_configs:
  - job_name: eduall-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: eduall
          __path__: /eduall/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'
      - multiline:
          firstline: '^\[\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '\[(?P<time>.*?)\] (?P<channel>[\w-]+)\.(?P<level>\w+): (?P<message>.*?)(?: (?P<context>\{.*\}))?$'
      - json:
          source: context
          expressions:
            view: view
            exception: exception
            userId: userId
          drop_malformed: true
      - timestamp:
          source: time
          format: '2006-01-02 15:04:05'
      - labels:
          level:
          channel:
          service:

  - job_name: timesheet-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: timesheet
          __path__: /timesheet/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'

  - job_name: assessment-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: assessment
          __path__: /assessment/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'

  - job_name: crm-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: crm
          __path__: /crm/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'

  - job_name: staging-crm-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: staging-crm
          __path__: /staging-crm/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'

  - job_name: editing-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: editing-backend
          __path__: /editing_v2-backend/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'

  - job_name: mentoring-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mentoring-backend
          __path__: /mentoring-backend/logs/*.log
    pipeline_stages:
      - drop:
          expression: '.{262144,}'